### ISSUE TITLE
Error parsing pthread_mutex_t

### ISSUE THREAD

**Issue by Dearth** [squaresLab/genprog-code#10]
Hello,

I am looking into GenProg's capability to repair a program which contains a concurrency error named banking.c.  I generated a small program containing a mutex protecting a global double.  When I run `repair` on banking.c I receive the following error:

cilRep: banking.c: parsing
Warning: Parsing raised Invalid_argument("index out of bounds")

banking.c[6:0-0] : syntax error
Parsing errorrepair aborting: Frontc.ParseError("Parse error")

Where line 6 in banking.c corresponds to the declaration of the global mutex.

If I expand the program into banking.i by running `gcc -E banking.c -lm -lpthread > banking.i` and run `repair` on banking.i, I receive the error:

cilRep: banking.i: parsing
/usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h[21:12-28] : syntax error
Parsing errorrepair aborting: Frontc.ParseError("Parse error")

I have included a tarball of the test directory containing the source code, test.sh, and all necessary test input files.

Any help is  appreciated,

Padraic Cashin
[banking.tar.gz](https://github.com/squaresLab/genprog-code/files/1823136/banking.tar.gz)

**Comment by jlacomis** [comment]
This is a problem with CIL having an issue parsing the code, not really a bug with GenProg. I suspect you need to use `-pthread` instead of `-lpthread` when preprocessing. I believe the former sets the flags for the preprocessor, while the latter only sets it for the linker.
