### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by thanhtoantnt** [squaresLab/genprog-code#13]
I am following your installation guide. When I try to run your provided scripts in **test** directory, I always got this message

> cilRep: preprocessing IO function signatures: /tmp/tmp1f886d.c /tmp/tmpb5ebe9.c
Segmentation fault (core dumped)

It happened both for the current version and the 3.2 release.

**Comment by yodahaji** [comment]
> 
> 
> I am following your installation guide. When I try to run your provided scripts in **test** directory, I always got this message
> 
> > cilRep: preprocessing IO function signatures: /tmp/tmp1f886d.c /tmp/tmpb5ebe9.c
> > Segmentation fault (core dumped)
> 
> It happened both for the current version and the 3.2 release.

Hi, I met the same question as you. Could you tell how to solve it?

**Comment by jlacomis** [comment]
I'm still getting reports of this issue so I'm reopening it. If anyone has any clues for what might cause this I'd appreciate a comment so I can preempt this error in the future. @thanhtoantnt were you able to solve this?

**Comment by pdreiter** [comment]
I had this same issue -----  I think I notated the solution as follows:
make sure you run
`make clean`
in the test directory - i think the committed output files are incompatible with newly generated files.
