### ISSUE TITLE
problem regarding setting environment variable CIL

### ISSUE THREAD

**Issue by Somdutta** [squaresLab/genprog-code#19]
Hi,

I have installed CIL using wget as discussed here, https://github.com/squaresLab/genprog-code/blob/master/README.md.  However, it says to set the environment variable CIL wherever cil.spec is in. After installing I do not see the file in the CIL directory. I have installed cil 1.7.3.

Could you please guide me regarding this?

Thanks

**Comment by jlacomis** [comment]
The instructions for installing CIL using `wget` are pretty old (note the sourceforge address), and I'm not sure they're the best way to go about it any more. Have you tried the recommended `opam` method?

**Comment by Somdutta** [comment]
I have OCAML 4.07.1 installed. When I tried opam install cil, I got the following error:
The following dependencies couldn't be met:
  - cil → ocaml < 4.06.0

**Comment by Somdutta** [comment]
My previous response I had tried it on MacOS. On Ubuntu 18.04.1 LTS, I installed using opam and moved to step 2 after running "opam install cil". I get the following error, "Makefile:41: *** Could not find CIL include path. Is $CIL set correctly?.  Stop.".

**Comment by jlacomis** [comment]
> I have OCAML 4.07.1 installed. When I tried opam install cil, I got the following error:
> The following dependencies couldn't be met:
> 
> * cil → ocaml < 4.06.0
This is a known issue with CIL where it won't compile on newer versions of OCaml. If you have `opam` 2 or greater you can use `opam switch create [name] [compiler version]` followed by `eval $(opam env)` to easily switch between compiler versions (you'll have to reinstall any packages you want to used on the new switch). If you have an older version of `opam` you can still use switches, but the commands are slightly different.

I'd recommend using OCaml 4.05

**Comment by jlacomis** [comment]
> My previous response I had tried it on MacOS. On Ubuntu 18.04.1 LTS, I installed using opam and moved to step 2 after running "opam install cil". I get the following error, "Makefile:41: *** Could not find CIL include path. Is $CIL set correctly?. Stop.".

This might be because you have the `CIL` environment variable set. Genprog will first check if `$CIL` is set and if so it'll use that instead of whatever's in your `PATH`. Try `unset CIL`.

**Comment by Somdutta** [comment]
Thanks I was able to install CIL with OCAML 4.05. 

I am bit confused about the process of running a program to repair. Does the repair under genprog-code-master -> src needs to run with command line options such as --program gcd.c? If so then what are the other options need to present and also what other files it requires to generate a repair.
Could you please point me any other documentation (if any ) of running the tool?
