### ISSUE TITLE
error while running a gcd.c code to repair

### ISSUE THREAD

**Issue by Somdutta** [squaresLab/genprog-code#20]

**Comment by Somdutta** [comment]
Hi,
I am running the repair program in the src folder. My command line input is 
./repair --compiler gcc --program gcd.c --pos-tests 10 --neg-tests 1 --test-script ./test.sh --minimization --no-test-cache

The error is:
cilRep: preprocessing IO function signatures: /var/folders/t0/fdbtzdd96fj8gl1466767dg80000gn/T/tmpa376f5.c /var/folders/t0/fdbtzdd96fj8gl1466767dg80000gn/T/tmpa410ef.c
/usr/include/sys/stdio.h[39:80-86] : syntax error
Parsing errorcilrep: fill_va_table: Frontc.parse: Frontc.ParseError("Parse error")

I get a repaired program which I don't think solves the test case where a=0 and b=55.  It is just adding an empty else block after the if check of (if(a==0)). The gcd.c and test.sh files are taken from test -> gcd-test.

Thanks

**Comment by clegoues** [comment]
Hi Somdutta,

What OS are you running on? How did you install Cil/OCaml?

Thanks!

**Comment by Somdutta** [comment]
Hi Claire,

I am running macOSHighSierra. I used OPAM to install CIL/OCAML.

Thanks

**Comment by Somdutta** [comment]
Hi Claire,

I am running macOSHighSierra. I used OPAM to install CIL/OCAML.

Thanks
Somdutta

**Comment by jlacomis** [comment]
> I get a repaired program which I don't think solves the test case where a=0 and b=55. It is just adding an empty else block after the if check of (if(a==0)). The gcd.c and test.sh files are taken from test -> gcd-test.

@Somdutta I'm a confused about how you got a repaired program if `repair` failed before it was able to parse the file. Were you able to successfully run it at least once?

**Comment by Somdutta** [comment]
No, everytime I ran the ./repair with command line parameters, I got the error that I mentioned earlier and repair.sanity.c file

**Comment by jlacomis** [comment]
Are you trying to run `repair` on files from inside `genprog-code/src`? I'd expect you to be in the folder `genprog-code/test/gcd-test` and run the command `../../src/repair configuration` (which loads config options from the `configuration` file) if you want to just run the most basic test.

**Comment by Somdutta** [comment]
Thanks. I was running it from the src folder. Now I ran it from the gcd-test folder with the command that you mentioned. I am getting the parse error that I had mentioned before and a coverage.c file is generated.

**Comment by jlacomis** [comment]
I'm now remembering the difficulties of running GenProg on recent versions of MacOS, and I'd guess the CIL preprocessor is choking on nonstandard MacOS preprocessor directives. I have a Mac version of `stdio.h` here and line 39 (where your error is reported) is:
```
int     renameat(int, const char *, int, const char *) __OSX_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0);
```
Character 80 is the start of `__MAC_10_10`, which I'm pretty sure would cause this failure.

Fun fact: `gcc` on MacOS isn't actually `gcc`, it's just an alias for `clang`. My solution to work around this was to install [gcc 8.3 from Homebrew](https://formulae.brew.sh/formula/gcc) and change my `--compile` argument to `/usr/local/bin/gcc-8`, which is pointed to actually-standard standard libraries.

I don't know if I'd recommend this option, it's pretty tedious, takes quite a while, and there's a lot of places to get stuck with confusing configurations. My first suggestion would be to either use a Linux machine or try running Linux in a VM, I think both would be a simpler option.

**Comment by Somdutta** [comment]
Thanks Jeremy. I will try to run it on Linux.
