### ISSUE TITLE
Porting to other languages

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [squaresLab/genprog-code#31]
I would like to use test this in other languages (Python in particular). Has anyone attempted/done that? What would the process be?

**Comment by monperrus** [comment]
FYI, https://github.com/squaresLab/genprog4java and https://github.com/SpoonLabs/astor are ports to Java.

**Comment by clegoues** [comment]
Old convo, but Andreas Zeller's debugging book, I understand, has an initial implementation of something similar for Python: https://www.debuggingbook.org/html/Repairer.html

It's not fully featured (since it's supposed to be educational) but it may be a reasonable place to start.

**Comment by monperrus** [comment]
For the record, in Python there is the "pyEDB - python Evolutionary DeBugging framework", see https://bitbucket.org/tomackling/pyedb/src/master/
