### ISSUE TITLE
Availability of GenProg ICSE 2012 benchmarks

### ISSUE THREAD

**Issue by bstee615** [squaresLab/genprog-code#36]
I'm trying to get the original format of the GenProg ICSE 2012 benchmark because I want to debug a tool that uses it (named [Angelix](http://angelix.io/)). I am trying to access the benchmark at this link: http://dijkstra.cs.virginia.edu/genprog/resources/genprog-icse2012-benchmarks. The site seems to be down. Is this benchmark available, and how would I go about getting it?

**Comment by jlacomis** [comment]
That server is run by Wes Weimer, who has since moved to Michigan. I can't find that exact location at the new URL, but maybe this link is a good place to start? https://dijkstra.eecs.umich.edu/genprog/resources/autorepairbenchmarks/

**Comment by clegoues** [comment]
That is the right URL, and I'll double check that the links are correct elsewhere.  Thanks!
